name: xuezi
description: A Chinese learning app.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  go_router: ^13.0.0
  flutter_bloc: ^8.1.3
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  get_it: ^7.6.4
  shared_preferences: ^2.2.2
  fl_chart: ^0.70.2
  flutter_card_swiper: ^6.0.0
  flutter_tts: ^3.8.5
  uuid: ^4.5.1
  injectable: ^2.5.0
  dartz: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  freezed: ^2.4.5
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
