name: xuezi
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.2
dependencies:
  go_router: ^14.8.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_tts: ^4.2.2
  flutter_card_swiper: ^7.0.2
  objectbox: ^4.1.0
  objectbox_flutter_libs: ^4.1.0
  # Clean Architecture dependencies
  get_it: ^7.6.7
  injectable: ^2.3.2
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  dartz: ^0.10.1
  bloc: ^8.1.3
  flutter_bloc: ^8.1.4
  equatable: ^2.0.5
  # Path handling
  path: ^1.9.0
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.3.6
  objectbox_generator: ^4.1.0
  # Clean Architecture dev dependencies
  injectable_generator: ^2.4.1
  freezed: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
